services:
  postgres_db:
    image: postgres:17
    volumes:
      - postgres_data_crew_forge_pg17:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crew_forge_network

  crewforge-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    working_dir: /app
    networks:
      - crew_forge_network

volumes:
  postgres_data_crew_forge_pg17:

networks:
  crew_forge_network:
    driver: bridge
