name: Django CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install

    - name: Enable caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run black
      run: uv run black --check --verbose .

    - name: Run isort
      run: uv run isort --check-only --diff .

    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        DJANGO_SETTINGS_MODULE: config.settings.local
        ENVIRONMENT: test
      run: |
        uv run pytest
